### ISSUE TITLE
Erro ao executar npm run start

### ISSUE THREAD

**Issue by topornet** [jediproject/ng-jedi-demo#2]
Ola,
Estou com problemas ao executar o npm run start.
Versao NPM : 3.5.0
Versao NODE : v4.2.2

Mac Os,

Segue abaixo o log:

0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node',
1 verbose cli   '/Users/valdomironeto/.node/bin/npm',
1 verbose cli   'run',
1 verbose cli   'start' ]
2 info using npm@3.5.0
3 info using node@v4.2.2
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle adoteme@0.0.1~prestart: adoteme@0.0.1
6 silly lifecycle adoteme@0.0.1~prestart: no script for prestart, continuing
7 info lifecycle adoteme@0.0.1~start: adoteme@0.0.1
8 verbose lifecycle adoteme@0.0.1~start: unsafe-perm in lifecycle true
9 verbose lifecycle adoteme@0.0.1~start: PATH: /Users/valdomironeto/.node/lib/node_modules/npm/bin/node-gyp-bin:/Users/valdomironeto/Documents/Develop/repository/cit/ng-jedi-demo/n$
10 verbose lifecycle adoteme@0.0.1~start: CWD: /Users/valdomironeto/Documents/Develop/repository/cit/ng-jedi-demo
11 silly lifecycle adoteme@0.0.1~start: Args: [ '-c',
11 silly lifecycle   'npm install && node node_modules/bower/bin/bower install && node node_modules/grunt-cli/bin/grunt develop && start node node_modules/apimocker/bin/apimocker.j$
12 info lifecycle adoteme@0.0.1~start: Failed to exec start script
13 verbose stack Error: adoteme@0.0.1 start: `npm install && node node_modules/bower/bin/bower install && node node_modules/grunt-cli/bin/grunt develop && start node node_modules/a$
13 verbose stack spawn ENOENT
13 verbose stack     at ChildProcess.<anonymous> (/Users/valdomironeto/.node/lib/node_modules/npm/lib/utils/spawn.js:17:16)
13 verbose stack     at emitTwo (events.js:87:13)
13 verbose stack     at ChildProcess.emit (events.js:172:7)
13 verbose stack     at maybeClose (internal/child_process.js:818:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
14 verbose pkgid adoteme@0.0.1
15 verbose cwd /Users/valdomironeto/Documents/Develop/repository/cit/ng-jedi-demo
16 error Darwin 15.0.0
17 error argv "/usr/local/bin/node" "/Users/valdomironeto/.node/bin/npm" "run" "start"
18 error node v4.2.2
19 error npm  v3.5.0
20 error file sh
21 error code ELIFECYCLE
22 error errno ENOENT
23 error syscall spawn
24 error adoteme@0.0.1 start: `npm install && node node_modules/bower/bin/bower install && node node_modules/grunt-cli/bin/grunt develop && start node node_modules/apimocker/bin/ap$
24 error spawn ENOENT
25 error Failed at the adoteme@0.0.1 start script 'npm install && node node_modules/bower/bin/bower install && node node_modules/grunt-cli/bin/grunt develop && start node node_modu$
25 error Make sure you have the latest version of node.js and npm installed.
25 error If you do, this is most likely a problem with the adoteme package,
25 error not with npm itself.
25 error Tell the author that this fails on your system:
25 error     npm install && node node_modules/bower/bin/bower install && node node_modules/grunt-cli/bin/grunt develop && start node node_modules/apimocker/bin/apimocker.js -c mock$
25 error You can get their info via:
25 error     npm owner ls adoteme
25 error There is likely additional logging output above.
26 verbose exit [ 1, true ]

**Comment by Tanato** [comment]
Faz um teste para mim, configura o seu git para usar o https ao invés de git:// com o comando abaixo

git config --global url."https://".insteadOf "git://"

**Comment by topornet** [comment]
Mesmo problema.

Fico no seu aguardo.

Att.

**Comment by hsbrighenti** [comment]
Oi @topornet subi agora scripts que são compatíveis com sistemas *nix :)

Por favor atualize o seu repositório e tente rodar:

```
   npm run start-nix
```

e me diga se funcionou :)

**Comment by topornet** [comment]
Olá,

Resolvido para Ubuntu, ainda não testei no Mac.

Obrigado.
