### ISSUE TITLE
Erro ao executar npm run start-nix

### ISSUE THREAD

**Issue by topornet** [jediproject/ng-jedi-demo#21]
Hi, below is the log

0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/nodejs', '/usr/bin/npm', 'run', 'start-nix' ]
2 info using npm@1.4.21
3 info using node@v0.10.25
4 verbose run-script [ 'prestart-nix', 'start-nix', 'poststart-nix' ]
5 info prestart-nix adoteme@0.0.1
6 info start-nix adoteme@0.0.1
7 verbose unsafe-perm in lifecycle true
8 info adoteme@0.0.1 Failed to exec start-nix script
9 error adoteme@0.0.1 start-nix: `npm install && node node_modules/bower/bin/bower install && node node_modules/gulp/bin/gulp.js && (node node_modules/apimocker/bin/apimocker.js -c mocks/config.json & node node_modules/json-server/bin/index.js mocks/animals/animals.json -p 3001 & node node_modules/http-server/bin/http-server -a localhost -p 8080)`
9 error Exit status 8
10 error Failed at the adoteme@0.0.1 start-nix script.
10 error This is most likely a problem with the adoteme package,
10 error not with npm itself.
10 error Tell the author that this fails on your system

I'm using ubuntu.

**Comment by topornet** [comment]
Fiz um teste com os comandos separados.

ng-jedi-demo$ start node node_modules/apimocker/bin/apimocker.js -c mocks/config.json
start: invalid option: -c
Try `start --help' for more information.

**Comment by fabioviana** [comment]
A versão que você está testando é antiga, esse erro já foi corrigido. Me
chame no HO que te passo mais detalhes.

Em qui, 18 de fev de 2016 18:17, Valdomiro Bilharvas Neto <
notifications@github.com> escreveu:
